title: focus-on-the-prize
hero_image: images/banner.png
description: focus-on-the-prize description
version: 4
listed: false
copyedit: false
last_tested: "2020-06-12"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
