title: Focus on the prize
hero_image: images/focus-banner.png
description: Improve your concentration by following the gift-box with the diamond inside while the other gift-boxes and surprise sprites try to distract you
version: 4
listed: false
copyedit: false
last_tested: "2020-06-12"
steps:
  - title: Introduction
  - title: Gift in a box
  - title: Move it
  - title: Empty boxes
  - title: "Did you get it right?"
  - title: More gifts  
  - title: Add a distraction
  - title: "Challenge: More distractions!"
    challenge: true
  - title: Demonstrate your project
  - title: "What next?"
