---
title: बक्षीसावर लक्ष केंद्रित करा
hero_image: images/focus-banner.png
description: इतर गिफ्ट बॉक्स आणि सरप्राईज तुमचे लक्ष विचलित करण्याचा प्रयत्न करत असताना त्यात डायमंड असलेल्या गिफ्ट बॉक्सचे अनुसरण करून तुमची एकाग्रता वाढवा
version: 4
listed: true
copyedit: true
last_tested: '2020-09-01'
steps:
  - title: परिचय
    completion: engaged
  - title: बॉक्समध्ये भेटवस्तू जोडा
  - title: भेटवस्तू बॉक्स हलवा
  - title: एक रिकामा बॉक्स तयार करा
  - title: उत्तरे उघड करा
  - title: अधिक भेटवस्तू जोडा
  - title: विकर्षण तयार करा
    completion: internal
  - title: आणखी जोडा
  - title: शेअर करा
  - title: पुढे काय?
