---
title: బహుమతిపై దృష్టి పెట్టండి
hero_image: images/focus-banner.png
description: ఇతర గిఫ్ట్ బాక్స్‌లు మరియు ఆశ్చర్య పరిచే sprite లు మీ దృష్టి మరల్చడానికి
  ప్రయత్నిస్తున్నప్పటికీ, దాని లోపల వజ్రం ఉన్న బహుమతి పెట్టెను అనుసరించడం ద్వారా మీ
  ఏకాగ్రతను మెరుగుపరచండి
version: 4
listed: true
copyedit: true
last_tested: '2020-09-01'
steps:
- title: పరిచయం
- title: ఒక పెట్టెలో బహుమతిని జోడించండి
- title: బహుమతి పెట్టెను తరలించండి
  completion:
  - engaged
- title: ఖాళీ పెట్టెను సృష్టించండి
- title: సమాధానాలు వెల్లడించండి
- title: మరిన్ని బహుమతులు జోడించండి
- title: ధ్యాస మరల్చండి
  completion:
  - internal
- title: మరిన్ని జోడించండి
- title: షేర్ చేయండి
- title: తర్వాత ఏంటి?
